"""Command line interface for Hypha."""

from __future__ import annotations

import argparse
import json
import sys

from hypha.agent import run_discovery, run_explain
from hypha.models import DiscoveryReport

BANNER = "hypha :: literature-based discovery engine"


def _print_report(report: DiscoveryReport) -> None:
    line = "=" * 72
    print(line)
    print(BANNER)
    print(line)
    sc = report.source_concept
    print(f"Topic        : {report.topic}")
    if sc:
        print(f"Source (A)   : {sc.name}  [level {sc.level}, {sc.works_count} works]")
    print(f"Source data  : {report.source_name}    Reasoner: {report.reasoner}")
    print(f"Stats        : {report.stats}")
    print(line)

    if not report.hypotheses:
        print("No novel cross-domain hypotheses surfaced for this topic.")
        print("\nTrace:")
        for ev in report.trace:
            print(f"  - [{ev.step}] {ev.detail}")
        return

    for i, h in enumerate(report.hypotheses, 1):
        link = h.bridge
        verdict = ""
        if h.verdict != "unverified":
            vn = f"{h.verified_novelty:.2f}" if h.verified_novelty is not None else "?"
            verdict = f"  [verdict={h.verdict.upper()} · verified novelty={vn}]"
        print(f"\n[{i}] {h.statement}{verdict}")
        print(f"    target (C)   : {link.target.name}")
        print(f"    bridges (B)  : {', '.join(b.name for b in link.bridges)}")
        print(
            f"    scores       : overall={link.score:.3f}  novelty={h.novelty_score:.3f}  "
            f"plausibility={h.plausibility_score:.3f}  "
            f"(bridges={link.bridge_support}, direct co-mentions={link.direct_cooccurrence})"
        )
        if h.verification_note:
            print(f"    verification : {h.verification_note}")
        print(f"    mechanism    : {h.mechanism}")
        print(f"    experiment   : {h.experiment}")
        if h.evidence:
            print("    evidence found:")
            for ev in h.evidence:
                yr = f" ({ev.year})" if ev.year else ""
                loc = f"  {ev.url}" if ev.url else ""
                print(f"        - [{ev.source}] {ev.title}{yr}{loc}")
        if h.supporting_works:
            print("    evidence     :")
            for w in h.supporting_works:
                cite = f"{w.title} ({w.year})"
                if w.url:
                    cite += f"  {w.url}"
                print(f"        - {cite}")
        print(f"    generated by : {h.generated_by}")

    print("\nTrace:")
    for ev in report.trace:
        print(f"  - [{ev.step}] {ev.detail}")


def cmd_discover(args: argparse.Namespace) -> int:
    report = run_discovery(
        args.topic,
        offline=args.offline,
        max_hypotheses=args.max,
        prefer_llm=not args.no_llm,
        verify=args.verify,
        evidence=None if args.evidence == "auto" else args.evidence,
        target=None if args.target == "any" else args.target,
    )
    if args.json:
        print(json.dumps(report.model_dump(), indent=2))
    else:
        _print_report(report)
    return 0


def cmd_explain(args: argparse.Namespace) -> int:
    report = run_explain(
        args.a,
        args.c,
        offline=args.offline,
        prefer_llm=not args.no_llm,
        verify=args.verify,
        evidence=None if args.evidence == "auto" else args.evidence,
    )
    if args.json:
        print(json.dumps(report.model_dump(), indent=2))
    else:
        _print_report(report)
    return 0


def cmd_backtest(args: argparse.Namespace) -> int:
    from hypha.backtest import backtest

    res = backtest(
        args.topic,
        args.year,
        k=args.k,
        emergence_threshold=args.threshold,
    )
    if args.json:
        import dataclasses

        print(json.dumps({"summary": res.summary(),
                          "links": [dataclasses.asdict(l) for l in res.links]}, indent=2))
        return 0

    line = "=" * 72
    print(line)
    print(f"{BANNER}  ::  back-test")
    print(line)
    s = res.summary()
    print(f"Topic            : {res.topic}  (source: {res.source_concept})")
    print(f"Split year       : {res.split_year}   (train <= {res.split_year}, test > {res.split_year})")
    print(f"Candidates scored: {s['candidates_scored']}   novel-as-of-{res.split_year}: {s['novel_as_of_split']}")
    print(f"Evaluated (top-k novel predictions): {s['evaluated_predictions']}")
    print(f"Hits (emerged)   : {s['hits']}")
    print(f"precision@{res.k:<3}     : {s['precision_at_k']:.3f}   (of top-k novel predictions, fraction that later emerged)")
    print(line)
    for l in res.links:
        flag = "HIT " if l.hit else "miss"
        print(
            f"[{flag}] {l.target:<32} past={l.past_comentions:<4} future={l.future_comentions:<6} "
            f"via {', '.join(l.bridges[:3])}"
        )
    return 0


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn

    uvicorn.run("hypha.api:app", host=args.host, port=args.port, reload=args.reload)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="hypha", description=BANNER)
    sub = parser.add_subparsers(dest="command", required=True)

    d = sub.add_parser("discover", help="Run literature-based discovery on a topic.")
    d.add_argument("topic", help="The source topic / concept A (e.g. 'Raynaud disease').")
    d.add_argument("--offline", action="store_true", help="Use the bundled offline fixture (no network).")
    d.add_argument("--no-llm", action="store_true", help="Force the deterministic reasoner even if an API key is set.")
    d.add_argument("--max", type=int, default=8, help="Maximum number of hypotheses to return.")
    d.add_argument(
        "--target",
        choices=["any", "drug", "chemical", "disease", "anatomy", "organism", "technique", "psychology", "phenomenon"],
        default="any",
        help="Constrain target concept C to a MeSH type (e.g. 'drug' for repurposing). Live mode only.",
    )
    d.add_argument("--verify", action="store_true", help="Verify each link against the literature and re-rank by verified novelty.")
    d.add_argument(
        "--evidence",
        choices=["auto", "openalex", "parallel", "paperclip"],
        default="auto",
        help="Evidence provider for --verify (auto picks the best available).",
    )
    d.add_argument("--json", action="store_true", help="Emit the full report as JSON.")
    d.set_defaults(func=cmd_discover)

    e = sub.add_parser("explain", help="Closed discovery: explain why A and C might be linked.")
    e.add_argument("a", help="Concept A (e.g. 'Raynaud disease').")
    e.add_argument("c", help="Concept C (e.g. 'Fish oil').")
    e.add_argument("--offline", action="store_true", help="Use the bundled offline fixture (no network).")
    e.add_argument("--no-llm", action="store_true", help="Force the deterministic reasoner.")
    e.add_argument("--verify", action="store_true", help="Verify the link against the literature.")
    e.add_argument("--evidence", choices=["auto", "openalex", "parallel", "paperclip"], default="auto")
    e.add_argument("--json", action="store_true", help="Emit the full report as JSON.")
    e.set_defaults(func=cmd_explain)

    b = sub.add_parser("backtest", help="Time-sliced validation: would past predictions have come true?")
    b.add_argument("topic", help="Source topic / concept A.")
    b.add_argument("--year", type=int, required=True, help="Split year Y (train on <=Y, test on >Y).")
    b.add_argument("--k", type=int, default=10, help="Number of top predicted links to score.")
    b.add_argument("--threshold", type=int, default=3, help="Min future co-mentions to count as 'emerged'.")
    b.add_argument("--json", action="store_true", help="Emit results as JSON.")
    b.set_defaults(func=cmd_backtest)

    s = sub.add_parser("serve", help="Start the web UI / API server.")
    s.add_argument("--host", default="127.0.0.1")
    s.add_argument("--port", type=int, default=8000)
    s.add_argument("--reload", action="store_true")
    s.set_defaults(func=cmd_serve)

    return parser


def main(argv: list[str] | None = None) -> int:
    from hypha.config import load_env

    load_env()
    parser = build_parser()
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
