"""Command line interface for Hypha."""

from __future__ import annotations

import argparse
import json
import sys

from hypha.agent import run_discovery
from hypha.models import DiscoveryReport

BANNER = "hypha :: literature-based discovery engine"


def _print_report(report: DiscoveryReport) -> None:
    line = "=" * 72
    print(line)
    print(BANNER)
    print(line)
    sc = report.source_concept
    print(f"Topic        : {report.topic}")
    if sc:
        print(f"Source (A)   : {sc.name}  [level {sc.level}, {sc.works_count} works]")
    print(f"Source data  : {report.source_name}    Reasoner: {report.reasoner}")
    print(f"Stats        : {report.stats}")
    print(line)

    if not report.hypotheses:
        print("No novel cross-domain hypotheses surfaced for this topic.")
        print("\nTrace:")
        for ev in report.trace:
            print(f"  - [{ev.step}] {ev.detail}")
        return

    for i, h in enumerate(report.hypotheses, 1):
        link = h.bridge
        print(f"\n[{i}] {h.statement}")
        print(f"    target (C)   : {link.target.name}")
        print(f"    bridges (B)  : {', '.join(b.name for b in link.bridges)}")
        print(
            f"    scores       : overall={link.score:.3f}  novelty={h.novelty_score:.3f}  "
            f"plausibility={h.plausibility_score:.3f}  "
            f"(bridges={link.bridge_support}, direct co-mentions={link.direct_cooccurrence})"
        )
        print(f"    mechanism    : {h.mechanism}")
        print(f"    experiment   : {h.experiment}")
        if h.supporting_works:
            print("    evidence     :")
            for w in h.supporting_works:
                cite = f"{w.title} ({w.year})"
                if w.url:
                    cite += f"  {w.url}"
                print(f"        - {cite}")
        print(f"    generated by : {h.generated_by}")

    print("\nTrace:")
    for ev in report.trace:
        print(f"  - [{ev.step}] {ev.detail}")


def cmd_discover(args: argparse.Namespace) -> int:
    report = run_discovery(
        args.topic,
        offline=args.offline,
        max_hypotheses=args.max,
        prefer_llm=not args.no_llm,
    )
    if args.json:
        print(json.dumps(report.model_dump(), indent=2))
    else:
        _print_report(report)
    return 0


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn

    uvicorn.run("hypha.api:app", host=args.host, port=args.port, reload=args.reload)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="hypha", description=BANNER)
    sub = parser.add_subparsers(dest="command", required=True)

    d = sub.add_parser("discover", help="Run literature-based discovery on a topic.")
    d.add_argument("topic", help="The source topic / concept A (e.g. 'Raynaud disease').")
    d.add_argument("--offline", action="store_true", help="Use the bundled offline fixture (no network).")
    d.add_argument("--no-llm", action="store_true", help="Force the deterministic reasoner even if an API key is set.")
    d.add_argument("--max", type=int, default=8, help="Maximum number of hypotheses to return.")
    d.add_argument("--json", action="store_true", help="Emit the full report as JSON.")
    d.set_defaults(func=cmd_discover)

    s = sub.add_parser("serve", help="Start the web UI / API server.")
    s.add_argument("--host", default="127.0.0.1")
    s.add_argument("--port", type=int, default=8000)
    s.add_argument("--reload", action="store_true")
    s.set_defaults(func=cmd_serve)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
